name: ClusterFuzzLite corpus pruning

"on":
  schedule:
    # An hour before batch fuzzing, so it starts from the pruned corpus.
    - cron: "0 5 * * *"

permissions: read-all

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  prune:
    name: Prune the stored corpus
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build fuzzers
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          language: rust
      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: prune
          storage-repo: ${{ github.server_url }}/${{ github.repository }}.git
          storage-repo-branch: clusterfuzzlite
